version: '3'
services:

  mysql:
      image: mysql:8.0
      ports:
          - 3306:3306
      environment:
          MYSQL_DATABASE: mydb
          MYSQL_USER: user
          MYSQL_PASSWORD: test
          MYSQL_ROOT_PASSWORD: test
      volumes:
          - ./dump:/docker-entrypoint-initdb.d
          - mysql:/var/lib/mysql
      # swarm 設定
      deploy:
        mode: replicated
        replicas: 1
        placement:
          constraints: [node.labels.mysql == true]
      networks:
          - my_network

  phpmyadmin:
      image: phpmyadmin/phpmyadmin:5.1.0
      links: 
          - mysql:db
      ports:
          - 8080:80
      depends_on:
        - mysql
      # swarm 設定
      deploy:
        mode: replicated
        replicas: 1
        placement:
          constraints: [node.labels.mysql == true]
      networks:
          - my_network
     
networks:
  my_network:
    # 加入已經存在的網路
    external: true

volumes:
    mysql:
        external: true