version: '3.0'
services:
  crawler_twse:
    build:
      context: .
      dockerfile: Dockerfile.cache
    image: crawler:7.2.1
    hostname: "twse"
    command: pipenv run celery -A financialdata.tasks.worker worker --loglevel=info --concurrency=1  --hostname=%h -Q twse
    restart: always
    environment:
      - TZ=Asia/Taipei
    networks:
        - my_network

  crawler_tpex:
    build:
      context: .
      dockerfile: Dockerfile.cache
    image: crawler:7.2.1
    hostname: "tpex"
    command: pipenv run celery -A financialdata.tasks.worker worker --loglevel=info --concurrency=1  --hostname=%h -Q tpex
    restart: always
    environment:
      - TZ=Asia/Taipei
    networks:
        - my_network

  crawler_taifex:
    build:
      context: .
      dockerfile: Dockerfile.cache
    image: crawler:7.2.1
    hostname: "taifex"
    command: pipenv run celery -A financialdata.tasks.worker worker --loglevel=info --concurrency=1  --hostname=%h -Q taifex
    restart: always
    environment:
      - TZ=Asia/Taipei
    networks:
        - my_network

networks:
  my_network:
    # 加入已經存在的網路
    external: true
