version: '3.0'
services:
  crawler_twse:
    build:
      context: .
      dockerfile: cache.Dockerfile
    image: crawler:dev
    hostname: "twse"
    command: pipenv run celery -A financialdata.tasks.worker worker --loglevel=info --concurrency=1  --hostname=%h -Q twse
    restart: always
    environment:
      - TZ=Asia/Taipei
    networks:
        - dev

networks:
  dev:
